const fs = require("fs");
const minify = require("html-minifier").minify;
const { dirname, join } = require('path');

const serverDistFolder = 'dist/ngsite-hacker/server';
const filePath = join(serverDistFolder, 'index.server.html');

fs.readFile(filePath, function (err, buf) {
  if (err) {
    console.log(err);
  } else {
    const originalValue = buf.toString();
    const minifiedValue = minify(originalValue, {
        caseSensitive: false,
        collapseBooleanAttributes: true,
        collapseInlineTagWhitespace: false,
        collapseWhitespace: true,
        conservativeCollapse: false,
        decodeEntities: true,
        html5: true,
        includeAutoGeneratedTags: false,
        keepClosingSlash: false,
        minifyCSS: true,
        minifyJS: true,
        preserveLineBreaks: false,
        preventAttributesEscaping: false,
        processConditionalComments: true,
        processScripts: ["text/html"],
        removeAttributeQuotes: true,
        removeComments: true,
        removeEmptyAttributes: true,
        removeEmptyElements: false,
        removeOptionalTags: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        removeTagWhitespace: true,
        sortAttributes: true,
        sortClassName: true,
        trimCustomFragments: true,
        useShortDoctype: true,
    });

    fs.writeFile(filePath, minifiedValue, function (err, data) {
        if (err) {
            console.log(err);
        } else {
            var diff = originalValue.length - minifiedValue.length;
            var savings = originalValue.length
                ? ((100 * diff) / originalValue.length).toFixed(2)
                : 0;
            console.log(
                "Successfully minified '" +
                    filePath +
                    "'" +
                    ". Original size: " +
                    originalValue.length +
                    ". Minified size: " +
                    minifiedValue.length +
                    ". Savings: " +
                    diff +
                    " (" +
                    savings +
                    "%)"
            );
        }
    });
  }
});
